version: 2
updates:
  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: weekly
    groups:
      frontend-minor-and-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: weekly
    groups:
      jvm-minor-and-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
