spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.flyway.enabled=true
spring.flyway.user=${SPRING_FLYWAY_USER}
spring.flyway.password=${SPRING_FLYWAY_PASSWORD}
spring.jpa.hibernate.ddl-auto=validate
server.servlet.session.cookie.secure=${SESSION_COOKIE_SECURE:true}
server.error.include-binding-errors=never
server.error.include-exception=false
server.error.include-message=never
server.error.include-stacktrace=never
springdoc.swagger-ui.enabled=false
springdoc.api-docs.enabled=false
