spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.flyway.enabled=true
spring.jpa.hibernate.ddl-auto=validate
server.servlet.session.cookie.secure=${SESSION_COOKIE_SECURE:true}
springdoc.swagger-ui.enabled=false
springdoc.api-docs.enabled=false
