spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.flyway.enabled=true
spring.jpa.hibernate.ddl-auto=validate
spring.output.ansi.enabled=always
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
vireo.starter.auth.docs-matchers=
