const en = {
  header: {
    title: "Items",
    description: "A complete responsive CRUD workflow backed by one Starter entity.",
    create: "Create item",
    createPreview: "Adds one record to this workspace",
  },
  search: { placeholder: "Search by name, description or status", clear: "Clear search" },
  results_one: "{{formattedCount}} result",
  results_other: "{{formattedCount}} results",
  filters: { open: "Filters", clearAll: "Clear all", clearAllLabel: "Clear all filters", title: "Filter items" },
  error: {
    message: "Items could not be loaded. Check the API connection, session, or active filters.",
    edit: "Edit",
    clear: "Clear",
  },
  empty: {
    filtered: "No items match the current search and filters.",
    first: "This workspace has no items yet.",
    none: "There are no items to show yet.",
    clear: "Clear search and filters",
    create: "Create the first item",
  },
  delete: {
    title: "Delete item?",
    message: "This permanently removes {{name}} from the active workspace.",
    confirm: "Delete",
  },
  table: {
    table: "Items",
    loadingTable: "Loading items",
    refreshing: "Refreshing items",
    noData: "No items match this search.",
    showMore: "Show more",
    showLess: "Show less",
    rowsPerPage: "Rows per page",
    paginationMoreThan: "{{from}}–{{to}} of more than {{to}}",
    paginationRange: "{{from}}–{{to}} of {{count}}",
    paginationItem: "Go to {{type}} page",
    filters: "Filters",
    clearFilters: "Clear",
    filtersDone: "Done",
    sortBy: "Sort by",
    sortDirection: "Sort direction",
    ascending: "Ascending",
    descending: "Descending",
    ascendingSortDirection: "Sort ascending",
    descendingSortDirection: "Sort descending",
  },
  filterFields: {
    name: "Name",
    description: "Description",
    quantity: "Quantity",
    status: "Status",
    statusValues: { DRAFT: "Draft", ACTIVE: "Active", ARCHIVED: "Archived" },
  },
} as const;
export default en;
