const en = {
  header: {
    back: "Back to Dev tools",
    title: "Multi-step form page",
    description: "A validated wizard backed by one form and Starter's typed multi-step navigation.",
  },
  aria: "Workspace setup",
  success: "Workspace “{{name}}” was submitted successfully.",
  steps: { details: "Workspace details", preferences: "Preferences", review: "Review" },
  sections: {
    details: { title: "Workspace details", description: "Define the workspace and its initial owner." },
    preferences: {
      title: "Workspace preferences",
      description: "Choose the initial access and communication defaults.",
    },
    review: { title: "Review workspace", description: "Confirm the complete setup before creating the workspace." },
  },
  fields: {
    workspaceName: { label: "Workspace name", placeholder: "Northstar workspace" },
    ownerEmail: { label: "Owner email", placeholder: "owner@example.com" },
    workspaceType: { label: "Workspace type", placeholder: "Choose a workspace type" },
    teamSize: { label: "Initial team size" },
    visibility: { label: "Visibility" },
    weeklyDigest: "Send the owner a weekly activity digest",
    notes: { label: "Setup notes", placeholder: "Add any context the team should see when joining." },
    confirmed: "I reviewed these workspace details and they are correct.",
  },
  workspaceTypes: { PRODUCT: "Product team", AGENCY: "Agency", INTERNAL: "Internal operations" },
  visibility: { PRIVATE: "Private", ORGANIZATION: "Organization" },
  review: {
    workspace: "Workspace",
    owner: "Owner",
    type: "Type",
    teamSize: "Team size",
    people: "{{count}} people",
    visibility: "Visibility",
    weeklyDigest: "Weekly digest",
    reviewStatus: "Review status",
    notProvided: "Not provided",
    notSelected: "Not selected",
    enabled: "Enabled",
    disabled: "Disabled",
    confirmed: "Confirmed",
    notConfirmed: "Not confirmed",
  },
  validation: {
    workspaceName: "Enter at least three characters.",
    ownerEmail: "Enter a valid owner email.",
    workspaceType: "Choose a workspace type.",
    wholeNumber: "Use a whole number.",
    teamSize: "Add at least one team member.",
    notes: "Keep the notes under 240 characters.",
  },
  actions: { submit: "Create workspace" },
} as const;
export default en;
