import type { WidenLeaves } from "@vireocodedev/localization";
import type entityQueryFiltersEn from "./entity-query-filters.en";

const entityQueryFiltersHr = {
  summary: {
    ariaLabel: "Aktivni filtri",
    relationOperator: "je",
    operators: {
      EQUALS: "je",
      NOT_EQUALS: "nije",
      CONTAINS: "sadrži",
      STARTS_WITH: "počinje s",
      ENDS_WITH: "završava s",
      IN: "jedno je od",
      GREATER_THAN: "veće je od",
      GREATER_OR_EQUAL: "najmanje je",
      LESS_THAN: "manje je od",
      LESS_OR_EQUAL: "najviše je",
      DATE_RANGE: "između je",
      IS_NULL: "prazno je",
      IS_NOT_NULL: "nije prazno",
    },
    from: "od {{value}}",
    through: "do {{value}}",
  },
  operators: {
    EQUALS: "Jednako",
    NOT_EQUALS: "Nije jednako",
    CONTAINS: "Sadrži",
    STARTS_WITH: "Počinje s",
    ENDS_WITH: "Završava s",
    IN: "Jedno je od",
    GREATER_THAN: "Veće od",
    GREATER_OR_EQUAL: "Veće ili jednako",
    LESS_THAN: "Manje od",
    LESS_OR_EQUAL: "Manje ili jednako",
    DATE_RANGE: "Između",
    IS_NULL: "Prazno",
    IS_NOT_NULL: "Nije prazno",
  },
  form: {
    noFields: "Ovaj entitet nema polja koja se mogu filtrirati.",
    noRules: "Nema primijenjenih strukturiranih filtara. Dodajte pravilo kako biste suzili rezultate.",
    rule: "Pravilo {{number}}",
    removeRule: "Ukloni pravilo {{number}}",
    field: "Polje",
    unavailableField: "Nedostupno polje",
    operator: "Operator",
    addFilter: "Dodaj filtar",
    value: "Vrijednost",
    values: "Vrijednosti",
    from: "Od",
    to: "Do",
    any: "Bilo koja",
    yes: "Da",
    no: "Ne",
    chooseValue: "Odaberite vrijednost",
    searchOptions: "Pretražite opcije",
    loadingOptions: "Učitavanje opcija",
    noOptions: "Nema odgovarajućih opcija",
    optionsLoadError: "Opcije nije moguće učitati.",
    optionsRefreshError: "Opcije nije moguće osvježiti. Prikazuju se posljednji spremljeni rezultati.",
    retryOptions: "Pokušaj ponovno",
  },
  validation: {
    unavailableField: "Ovo polje filtra više nije dostupno.",
    operator: "Odaberite dostupni operator.",
    relation: "Odaberite najmanje jednu opciju.",
    value: "Unesite vrijednost filtra.",
    duplicate: "Ovo pravilo filtra je duplicirano.",
    dateRange: "Unesite početni datum, završni datum ili oba.",
  },
  overlay: {
    close: "Zatvori filtre",
    loading: "Učitavanje polja filtra",
    loadError: "Polja filtra nije moguće učitati.",
    staleError: "Polja filtra nije moguće osvježiti. Prikazuje se posljednja spremljena definicija.",
    retry: "Pokušaj ponovno",
    clear: "Očisti",
    cancel: "Odustani",
    apply: "Primijeni",
  },
} satisfies WidenLeaves<typeof entityQueryFiltersEn>;

export default entityQueryFiltersHr;
