const entityQueryFiltersEn = {
  summary: {
    ariaLabel: "Active filters",
    relationOperator: "is",
    operators: {
      EQUALS: "is",
      NOT_EQUALS: "is not",
      CONTAINS: "contains",
      STARTS_WITH: "starts with",
      ENDS_WITH: "ends with",
      IN: "is one of",
      GREATER_THAN: "is greater than",
      GREATER_OR_EQUAL: "is at least",
      LESS_THAN: "is less than",
      LESS_OR_EQUAL: "is at most",
      DATE_RANGE: "is between",
      IS_NULL: "is empty",
      IS_NOT_NULL: "is not empty",
    },
    from: "from {{value}}",
    through: "through {{value}}",
  },
  operators: {
    EQUALS: "Equals",
    NOT_EQUALS: "Does not equal",
    CONTAINS: "Contains",
    STARTS_WITH: "Starts with",
    ENDS_WITH: "Ends with",
    IN: "Is one of",
    GREATER_THAN: "Greater than",
    GREATER_OR_EQUAL: "Greater than or equal",
    LESS_THAN: "Less than",
    LESS_OR_EQUAL: "Less than or equal",
    DATE_RANGE: "Is between",
    IS_NULL: "Is empty",
    IS_NOT_NULL: "Is not empty",
  },
  form: {
    noFields: "This entity has no filterable fields.",
    noRules: "No structured filters are applied. Add a rule to narrow the results.",
    rule: "Rule {{number}}",
    removeRule: "Remove rule {{number}}",
    field: "Field",
    unavailableField: "Unavailable field",
    operator: "Operator",
    addFilter: "Add filter",
    value: "Value",
    values: "Values",
    from: "From",
    to: "To",
    any: "Any",
    yes: "Yes",
    no: "No",
    chooseValue: "Choose a value",
    searchOptions: "Search options",
  },
  validation: {
    unavailableField: "This filter field is no longer available.",
    operator: "Choose an available operator.",
    relation: "Choose at least one option.",
    value: "Enter a filter value.",
    duplicate: "This filter rule is duplicated.",
    dateRange: "Enter a start date, an end date, or both.",
  },
  overlay: {
    close: "Close filters",
    loading: "Loading filter fields",
    loadError: "Filter fields could not be loaded.",
    retry: "Retry",
    clear: "Clear",
    cancel: "Cancel",
    apply: "Apply",
  },
} as const;

export default entityQueryFiltersEn;
